/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AIcharacter: typeof import('./src/components/AIcharacter.vue')['default']
    ChatInput: typeof import('./src/components/chatInput.vue')['default']
    CreatePersonality: typeof import('./src/components/CreatePersonality.vue')['default']
    CreatePrompt: typeof import('./src/components/CreatePrompt.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    EnterKey: typeof import('./src/components/EnterKey.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LookDetailsPrompt: typeof import('./src/components/LookDetailsPrompt.vue')['default']
    ModalItem: typeof import('./src/components/ModalItem.vue')['default']
    Openinterface: typeof import('./src/components/Openinterface.vue')['default']
    PromptLibrary: typeof import('./src/components/PromptLibrary.vue')['default']
    PromptShop: typeof import('./src/components/PromptShop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
